
/* Drop Tables */
/*
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
*/



/* Create Tables */

CREATE TABLE BOARD
(
	ID number NOT NULL,
	TITLE nvarchar2(100) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	USERNAME varchar2(20) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE MEMBER
(
	USERNAME varchar2(20) NOT NULL,
	PASSWORD varchar2(20) NOT NULL,
	 NAME nvarchar2(20) NOT NULL,
	GENDER nvarchar2(20) NOT NULL,
	INTER nvarchar2(20) NOT NULL,
	 GRADE nvarchar2(20) NOT NULL,
	INFO nvarchar2(2000) NOT NULL,
	REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (USERNAME)
);



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBER (USERNAME)
;

CREATE SEQUENCE SEQ_BOARD
NOCYCLE
NOCACHE;


